### ISSUE TITLE
Get approval from @dacioromero

### ISSUE THREAD

**Issue by mpdude** [mpdude/yarn-unlock-indirect-dependencies#1]
Hey @dacioromero,

I found the script you provided at https://github.com/yarnpkg/yarn/issues/4986#issuecomment-598746788 useful and slightly extended it.

Would it be OK for you if we release this under the MIT license?

**Comment by dacioromero** [comment]
As long as you credit me somewhere it's all good by me

EDIT: Just saw that you credited me in the README, so you're good to go

**Comment by mpdude** [comment]
Thank you!
